# Generated by Django 6.0.5 on 2026-08-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('fecha', models.DateField()),
                ('diagnostico', models.TextField()),
            ],
        ),
    ]
